<template><view class="page"><view class="hero"><text class="eyebrow">一字一世界 · 一念一生名</text><text class="title">{{ greeting }}，{{ user?.username || '朋友' }}</text><text class="subtitle">从命名灵感到品牌落地，在手机上继续你的项目。</text><view class="hero-stat"><view><text>{{ balance }}</text><text>可用次数</text></view><view><text>{{ dashboard?.projects_total || 0 }}</text><text>命名项目</text></view><view><text>{{ dashboard?.reports_total || 0 }}</text><text>报告</text></view></view></view><text class="section-title">常用服务</text><view class="grid"><view v-for="item in services" :key="item.url" class="service card" @click="open(item.url)"><text class="service-icon">{{ item.icon }}</text><text class="card-title">{{ item.name }}</text><text class="muted">{{ item.desc }}</text></view></view><view v-if="loading" class="loading">正在同步账号数据…</view></view></template>
<script setup>
import {computed,ref} from 'vue';import{onShow}from'@dcloudio/uni-app';import{api,getSession,requireLogin}from'../../api'
const user=ref(getSession()?.user),balance=ref(0),dashboard=ref(null),loading=ref(false)
const services=[{name:'专属知识库',icon:'知',desc:'上传品牌资料',url:'/pages/knowledge/knowledge'},{name:'我的任务',icon:'任',desc:'查看后台进度',url:'/pages/tasks/tasks'},{name:'专家服务',icon:'专',desc:'专家精批与入驻',url:'/pages/experts/experts'},{name:'开放平台',icon:'API',desc:'管理接口接入',url:'/pages/developers/developers'}]
const greeting=computed(()=>new Date().getHours()<12?'早上好':new Date().getHours()<18?'下午好':'晚上好')
function open(url){uni.navigateTo({url})}
async function load(){if(!requireLogin())return;loading.value=true;try{const [me,b,d]=await Promise.all([api.me(),api.balance(),api.dashboard()]);user.value=me;balance.value=b.balance;dashboard.value=d}catch(e){uni.showToast({title:e.message,icon:'none'})}finally{loading.value=false}}
onShow(load)
</script>
<style scoped>.hero-stat{display:grid;grid-template-columns:repeat(3,1fr);gap:12rpx;margin-top:34rpx}.hero-stat view{padding:18rpx 10rpx;background:rgba(255,255,255,.1);border-radius:14rpx;text-align:center}.hero-stat text{display:block}.hero-stat text:first-child{font-size:38rpx;font-weight:700}.hero-stat text:last-child{font-size:20rpx;color:rgba(255,255,255,.65)}.service{min-height:240rpx;margin:0}.service-icon{display:grid;place-items:center;width:66rpx;height:66rpx;background:#f1e5d8;color:#a94439;border-radius:18rpx;font-weight:700;margin-bottom:20rpx}.service .muted{display:block;margin-top:10rpx}</style>
