@baseUrl = http://127.0.0.1:8000
@email = 1114857160@qq.com
@password = 123456


### 1. 测试邮件发送
GET {{baseUrl}}/mail/test?email={{email}}


### 2. 获取注册验证码
GET {{baseUrl}}/auth/code?email={{email}}


### 3. 注册用户
# 请把 code 修改成邮箱里收到的真实验证码
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "{{email}}",
  "username": "testuser",
  "password": "{{password}}",
  "confirm_password": "{{password}}",
  "code": "3681"
}


### 4. 登录并获取 access_token 和 refresh_token
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}


### 5. 使用 access token 访问需要登录的接口
GET {{baseUrl}}/auth/verify-access
Authorization: Bearer {{login.response.body.$.access_token}}


### 6. 使用 refresh token 获取新的 access token
# @name refreshToken
POST {{baseUrl}}/auth/refresh
Authorization: Bearer {{login.response.body.$.refresh_token}}


### 7. 使用新 access token 再次访问受保护接口
GET {{baseUrl}}/auth/verify-access
Authorization: Bearer {{refreshToken.response.body.$.access_token}}


### 8. 错误测试：拿 refresh token 访问 access 接口
GET {{baseUrl}}/auth/verify-access
Authorization: Bearer {{login.response.body.$.refresh_token}}


### 9. 错误测试：拿 access token 请求刷新
POST {{baseUrl}}/auth/refresh
Authorization: Bearer {{login.response.body.$.access_token}}


### 10. 错误测试：使用伪造 Token
GET {{baseUrl}}/auth/verify-access
Authorization: Bearer abc.def.ghi


### 11. 错误测试：完全不传 Token
GET {{baseUrl}}/auth/verify-access


###  登录进行

POST http://127.0.0.1:8000/name/get_names
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.access_token}}

{
  "surname": "陈",
  "length": "两字",
  "gender": "男",
  "other": "单字，简单一点，寄托我对他的期望"
}


### 查询剩余次数
### 查询剩余次数
GET http://127.0.0.1:8000/credit/balance
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJ0eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg0NTM0MjIzfQ.XqlVK8JWHtUmj0Zt13vFuAXs6MJ9HQ93jO79TNJW1so

