"""add expert services

Revision ID: k08b4d27e1a6
Revises: j97a3c16d0f5
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "k08b4d27e1a6"
down_revision: Union[str, None] = "j97a3c16d0f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table("expert_profile", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("user_id", sa.Integer(), nullable=False), sa.Column("display_name", sa.String(100), nullable=False), sa.Column("title", sa.String(120), nullable=False), sa.Column("specialties", sa.String(500), nullable=False), sa.Column("bio", sa.Text(), nullable=False), sa.Column("experience_years", sa.Integer(), nullable=False), sa.Column("portfolio", sa.Text(), nullable=False), sa.Column("status", sa.String(20), nullable=False), sa.Column("review_note", sa.String(500), nullable=False), sa.Column("rating_average", sa.Numeric(3, 2), nullable=False), sa.Column("rating_count", sa.Integer(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("reviewed_at", sa.DateTime(), nullable=True), sa.Column("updated_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"), sa.UniqueConstraint("user_id"))
    op.create_index("ix_expert_profile_user_id", "expert_profile", ["user_id"]); op.create_index("ix_expert_profile_status", "expert_profile", ["status"])
    op.create_table("expert_package", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("expert_id", sa.Integer(), nullable=False), sa.Column("name", sa.String(120), nullable=False), sa.Column("description", sa.Text(), nullable=False), sa.Column("price", sa.Numeric(10, 2), nullable=False), sa.Column("delivery_days", sa.Integer(), nullable=False), sa.Column("revision_count", sa.Integer(), nullable=False), sa.Column("is_active", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["expert_id"], ["expert_profile.id"], ondelete="CASCADE"))
    op.create_index("ix_expert_package_expert_id", "expert_package", ["expert_id"]); op.create_index("ix_expert_package_is_active", "expert_package", ["is_active"])
    op.create_table("expert_order", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("order_no", sa.String(50), nullable=False, unique=True), sa.Column("user_id", sa.Integer(), nullable=False), sa.Column("expert_id", sa.Integer(), nullable=False), sa.Column("package_id", sa.Integer(), nullable=False), sa.Column("project_id", sa.Integer(), nullable=True), sa.Column("client_request_id", sa.String(100), nullable=False), sa.Column("package_name", sa.String(120), nullable=False), sa.Column("expert_name", sa.String(100), nullable=False), sa.Column("amount", sa.Numeric(10, 2), nullable=False), sa.Column("requirement", sa.Text(), nullable=False), sa.Column("status", sa.String(20), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("accepted_at", sa.DateTime(), nullable=True), sa.Column("delivered_at", sa.DateTime(), nullable=True), sa.Column("completed_at", sa.DateTime(), nullable=True), sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="RESTRICT"), sa.ForeignKeyConstraint(["expert_id"], ["expert_profile.id"], ondelete="RESTRICT"), sa.ForeignKeyConstraint(["package_id"], ["expert_package.id"], ondelete="RESTRICT"), sa.ForeignKeyConstraint(["project_id"], ["naming_project.id"], ondelete="SET NULL"), sa.UniqueConstraint("user_id", "client_request_id", name="uq_expert_order_user_request"))
    for col in ("order_no", "user_id", "expert_id", "package_id", "project_id", "status"): op.create_index(f"ix_expert_order_{col}", "expert_order", [col])
    op.create_table("expert_delivery", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("order_id", sa.Integer(), nullable=False, unique=True), sa.Column("title", sa.String(160), nullable=False), sa.Column("content", sa.Text(), nullable=False), sa.Column("attachment_url", sa.String(500), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["order_id"], ["expert_order.id"], ondelete="CASCADE")); op.create_index("ix_expert_delivery_order_id", "expert_delivery", ["order_id"])
    op.create_table("expert_review", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("order_id", sa.Integer(), nullable=False, unique=True), sa.Column("user_id", sa.Integer(), nullable=False), sa.Column("expert_id", sa.Integer(), nullable=False), sa.Column("rating", sa.Integer(), nullable=False), sa.Column("content", sa.String(1000), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["order_id"], ["expert_order.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["expert_id"], ["expert_profile.id"], ondelete="CASCADE")); op.create_index("ix_expert_review_order_id", "expert_review", ["order_id"]); op.create_index("ix_expert_review_user_id", "expert_review", ["user_id"]); op.create_index("ix_expert_review_expert_id", "expert_review", ["expert_id"])
    op.create_table("expert_settlement", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("order_id", sa.Integer(), nullable=False, unique=True), sa.Column("expert_id", sa.Integer(), nullable=False), sa.Column("gross_amount", sa.Numeric(10, 2), nullable=False), sa.Column("platform_fee", sa.Numeric(10, 2), nullable=False), sa.Column("net_amount", sa.Numeric(10, 2), nullable=False), sa.Column("status", sa.String(20), nullable=False), sa.Column("settled_at", sa.DateTime(), nullable=True), sa.Column("created_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["order_id"], ["expert_order.id"], ondelete="RESTRICT"), sa.ForeignKeyConstraint(["expert_id"], ["expert_profile.id"], ondelete="RESTRICT")); op.create_index("ix_expert_settlement_order_id", "expert_settlement", ["order_id"]); op.create_index("ix_expert_settlement_expert_id", "expert_settlement", ["expert_id"]); op.create_index("ix_expert_settlement_status", "expert_settlement", ["status"])
    role = sa.table("role", sa.column("code", sa.String), sa.column("name", sa.String), sa.column("description", sa.String), sa.column("is_system", sa.Boolean))
    permission = sa.table("permission", sa.column("code", sa.String), sa.column("name", sa.String), sa.column("description", sa.String))
    op.bulk_insert(role, [{"code": "expert", "name": "认证专家", "description": "通过审核的命名专家", "is_system": True}])
    op.bulk_insert(permission, [{"code": "expert.work", "name": "专家工作台", "description": "管理专家套餐、订单、交付与结算"}, {"code": "experts.manage", "name": "管理专家服务", "description": "审核专家并查询专家订单"}, {"code": "settlements.manage", "name": "管理专家结算", "description": "查询并确认专家结算"}])
    op.execute(sa.text("INSERT INTO role_permission (role_id, permission_id) SELECT r.id, p.id FROM role r JOIN permission p ON p.code = 'expert.work' WHERE r.code = 'expert'"))
    op.execute(sa.text("INSERT INTO role_permission (role_id, permission_id) SELECT r.id, p.id FROM role r JOIN permission p ON p.code IN ('experts.manage','settlements.manage') WHERE r.code = 'admin'"))


def downgrade() -> None:
    op.execute(sa.text("DELETE rp FROM role_permission rp JOIN permission p ON p.id=rp.permission_id WHERE p.code IN ('expert.work','experts.manage','settlements.manage')")); op.execute(sa.text("DELETE FROM permission WHERE code IN ('expert.work','experts.manage','settlements.manage')")); op.execute(sa.text("DELETE FROM user_role WHERE role_id IN (SELECT id FROM role WHERE code='expert')")); op.execute(sa.text("DELETE FROM role WHERE code='expert'"))
    op.drop_table("expert_settlement"); op.drop_table("expert_review"); op.drop_table("expert_delivery"); op.drop_table("expert_order"); op.drop_table("expert_package"); op.drop_table("expert_profile")
