"""add developer platform

Revision ID: m20d6f49a3c8
Revises: l19c5e38f2b7
"""
from typing import Sequence, Union
from datetime import datetime
from alembic import op
import sqlalchemy as sa

revision: str = "m20d6f49a3c8"
down_revision: Union[str, None] = "l19c5e38f2b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    op.create_table("developer_account",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("user_id",sa.Integer(),nullable=False),sa.Column("company_name",sa.String(160),nullable=False),sa.Column("contact_name",sa.String(100),nullable=False),sa.Column("use_case",sa.Text(),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False),sa.ForeignKeyConstraint(["user_id"],["user.id"],ondelete="CASCADE"),sa.UniqueConstraint("user_id"));op.create_index("ix_developer_account_user_id","developer_account",["user_id"]);op.create_index("ix_developer_account_status","developer_account",["status"])
    op.create_table("developer_api_key",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("developer_id",sa.Integer(),nullable=False),sa.Column("name",sa.String(100),nullable=False),sa.Column("key_prefix",sa.String(20),nullable=False),sa.Column("key_hash",sa.String(64),nullable=False,unique=True),sa.Column("status",sa.String(20),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False),sa.Column("last_used_at",sa.DateTime(),nullable=True),sa.Column("revoked_at",sa.DateTime(),nullable=True),sa.ForeignKeyConstraint(["developer_id"],["developer_account.id"],ondelete="CASCADE"));op.create_index("ix_developer_api_key_developer_id","developer_api_key",["developer_id"]);op.create_index("ix_developer_api_key_key_prefix","developer_api_key",["key_prefix"]);op.create_index("ix_developer_api_key_status","developer_api_key",["status"])
    op.create_table("api_plan",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("name",sa.String(100),nullable=False),sa.Column("description",sa.String(500),nullable=False),sa.Column("price",sa.Numeric(10,2),nullable=False),sa.Column("quota_calls",sa.Integer(),nullable=False),sa.Column("validity_days",sa.Integer(),nullable=False),sa.Column("is_active",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False));op.create_index("ix_api_plan_is_active","api_plan",["is_active"])
    op.create_table("developer_subscription",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("developer_id",sa.Integer(),nullable=False),sa.Column("plan_id",sa.Integer(),nullable=False),sa.Column("quota_total",sa.Integer(),nullable=False),sa.Column("quota_used",sa.Integer(),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("starts_at",sa.DateTime(),nullable=False),sa.Column("expires_at",sa.DateTime(),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False),sa.ForeignKeyConstraint(["developer_id"],["developer_account.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["plan_id"],["api_plan.id"],ondelete="RESTRICT"));op.create_index("ix_developer_subscription_developer_id","developer_subscription",["developer_id"]);op.create_index("ix_developer_subscription_plan_id","developer_subscription",["plan_id"]);op.create_index("ix_developer_subscription_status","developer_subscription",["status"])
    op.create_table("api_usage_log",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("developer_id",sa.Integer(),nullable=False),sa.Column("api_key_id",sa.Integer(),nullable=False),sa.Column("subscription_id",sa.Integer(),nullable=True),sa.Column("request_id",sa.String(100),nullable=False),sa.Column("endpoint",sa.String(100),nullable=False),sa.Column("units",sa.Integer(),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("response_data",sa.JSON(),nullable=True),sa.Column("error_message",sa.String(1000),nullable=False),sa.Column("latency_ms",sa.Integer(),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False),sa.ForeignKeyConstraint(["developer_id"],["developer_account.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["api_key_id"],["developer_api_key.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["subscription_id"],["developer_subscription.id"],ondelete="SET NULL"),sa.UniqueConstraint("api_key_id","request_id",name="uq_api_usage_key_request"))
    for c in ("developer_id","api_key_id","subscription_id","endpoint","status","created_at"):op.create_index(f"ix_api_usage_log_{c}","api_usage_log",[c])
    plan=sa.table("api_plan",sa.column("name",sa.String),sa.column("description",sa.String),sa.column("price",sa.Numeric),sa.column("quota_calls",sa.Integer),sa.column("validity_days",sa.Integer),sa.column("is_active",sa.Boolean),sa.column("created_at",sa.DateTime))
    op.bulk_insert(plan,[{"name":"开发者体验包","description":"免费体验开放命名 API","price":0,"quota_calls":20,"validity_days":30,"is_active":True,"created_at":datetime.now()}])
    permission=sa.table("permission",sa.column("code",sa.String),sa.column("name",sa.String),sa.column("description",sa.String));op.bulk_insert(permission,[{"code":"developers.manage","name":"开放平台管理","description":"管理开发者、API 套餐和额度授予"}]);op.execute(sa.text("INSERT INTO role_permission (role_id,permission_id) SELECT r.id,p.id FROM role r JOIN permission p ON p.code='developers.manage' WHERE r.code='admin'"))

def downgrade() -> None:
    op.execute(sa.text("DELETE rp FROM role_permission rp JOIN permission p ON p.id=rp.permission_id WHERE p.code='developers.manage'"));op.execute(sa.text("DELETE FROM permission WHERE code='developers.manage'"));op.drop_table("api_usage_log");op.drop_table("developer_subscription");op.drop_table("api_plan");op.drop_table("developer_api_key");op.drop_table("developer_account")
