"""add growth and distribution

Revision ID: n31e7a50b4d9
Revises: m20d6f49a3c8
"""
from typing import Sequence,Union
from datetime import datetime,timedelta
from alembic import op
import sqlalchemy as sa
revision="n31e7a50b4d9";down_revision="m20d6f49a3c8";branch_labels=None;depends_on=None
def upgrade():
    op.create_table("growth_campaign",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("name",sa.String(120),nullable=False),sa.Column("description",sa.String(500),nullable=False),sa.Column("inviter_reward",sa.Integer(),nullable=False),sa.Column("invitee_reward",sa.Integer(),nullable=False),sa.Column("commission_rate",sa.Numeric(5,4),nullable=False),sa.Column("starts_at",sa.DateTime(),nullable=False),sa.Column("ends_at",sa.DateTime(),nullable=False),sa.Column("is_active",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False));op.create_index("ix_growth_campaign_is_active","growth_campaign",["is_active"])
    op.create_table("promotion_code",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("user_id",sa.Integer(),nullable=False),sa.Column("code",sa.String(20),nullable=False,unique=True),sa.Column("status",sa.String(20),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False),sa.ForeignKeyConstraint(["user_id"],["user.id"],ondelete="CASCADE"),sa.UniqueConstraint("user_id"));op.create_index("ix_promotion_code_user_id","promotion_code",["user_id"]);op.create_index("ix_promotion_code_code","promotion_code",["code"]);op.create_index("ix_promotion_code_status","promotion_code",["status"])
    op.create_table("referral_relation",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("inviter_id",sa.Integer(),nullable=False),sa.Column("invitee_id",sa.Integer(),nullable=False),sa.Column("promotion_code_id",sa.Integer(),nullable=False),sa.Column("campaign_id",sa.Integer(),nullable=True),sa.Column("created_at",sa.DateTime(),nullable=False),sa.ForeignKeyConstraint(["inviter_id"],["user.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["invitee_id"],["user.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["promotion_code_id"],["promotion_code.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["campaign_id"],["growth_campaign.id"],ondelete="SET NULL"),sa.UniqueConstraint("invitee_id",name="uq_referral_invitee"));op.create_index("ix_referral_relation_inviter_id","referral_relation",["inviter_id"]);op.create_index("ix_referral_relation_invitee_id","referral_relation",["invitee_id"])
    op.create_table("referral_reward",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("relation_id",sa.Integer(),nullable=False),sa.Column("user_id",sa.Integer(),nullable=False),sa.Column("beneficiary_type",sa.String(20),nullable=False),sa.Column("credit_count",sa.Integer(),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False),sa.ForeignKeyConstraint(["relation_id"],["referral_relation.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["user_id"],["user.id"],ondelete="CASCADE"),sa.UniqueConstraint("relation_id","beneficiary_type",name="uq_referral_reward_relation_type"));op.create_index("ix_referral_reward_relation_id","referral_reward",["relation_id"]);op.create_index("ix_referral_reward_user_id","referral_reward",["user_id"])
    op.create_table("referral_commission",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("relation_id",sa.Integer(),nullable=False),sa.Column("order_id",sa.Integer(),nullable=False,unique=True),sa.Column("inviter_id",sa.Integer(),nullable=False),sa.Column("order_amount",sa.Numeric(10,2),nullable=False),sa.Column("commission_rate",sa.Numeric(5,4),nullable=False),sa.Column("commission_amount",sa.Numeric(10,2),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False),sa.Column("reversed_at",sa.DateTime(),nullable=True),sa.ForeignKeyConstraint(["relation_id"],["referral_relation.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["order_id"],["user_order.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["inviter_id"],["user.id"],ondelete="RESTRICT"));op.create_index("ix_referral_commission_relation_id","referral_commission",["relation_id"]);op.create_index("ix_referral_commission_order_id","referral_commission",["order_id"]);op.create_index("ix_referral_commission_inviter_id","referral_commission",["inviter_id"]);op.create_index("ix_referral_commission_status","referral_commission",["status"])
    now=datetime.now();campaign=sa.table("growth_campaign",sa.column("name",sa.String),sa.column("description",sa.String),sa.column("inviter_reward",sa.Integer),sa.column("invitee_reward",sa.Integer),sa.column("commission_rate",sa.Numeric),sa.column("starts_at",sa.DateTime),sa.column("ends_at",sa.DateTime),sa.column("is_active",sa.Boolean),sa.column("created_at",sa.DateTime));op.bulk_insert(campaign,[{"name":"好友共创计划","description":"邀请好友注册，双方获得命名次数；好友首次及后续付费产生推广佣金记录。","inviter_reward":1,"invitee_reward":1,"commission_rate":0.10,"starts_at":now-timedelta(days=1),"ends_at":now+timedelta(days=365),"is_active":True,"created_at":now}])
    permission=sa.table("permission",sa.column("code",sa.String),sa.column("name",sa.String),sa.column("description",sa.String));op.bulk_insert(permission,[{"code":"growth.manage","name":"增长活动管理","description":"管理邀请活动与佣金记录"}]);op.execute(sa.text("INSERT INTO role_permission (role_id,permission_id) SELECT r.id,p.id FROM role r JOIN permission p ON p.code='growth.manage' WHERE r.code='admin'"))
def downgrade():
    op.execute(sa.text("DELETE rp FROM role_permission rp JOIN permission p ON p.id=rp.permission_id WHERE p.code='growth.manage'"));op.execute(sa.text("DELETE FROM permission WHERE code='growth.manage'"));op.drop_table("referral_commission");op.drop_table("referral_reward");op.drop_table("referral_relation");op.drop_table("promotion_code");op.drop_table("growth_campaign")
